controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute
app.swagger_ui:
  path: /v1/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
